version: '3'

services:
  web:
    build: .
    depends_on:
    - postgres
    ports:
      - "8000:8000"
    volumes:
      - /./usr/src/app:ro
    command:
      - uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DATABASE_USERNAME=postgres
      - DATABASE_NAME=fastapi
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PASSWORD=Bright#1270

  postgres:
      image: postgres:latest
      environment:
        - POSTGRES_PASSWORD=Bright#1270
         - POSTGRES_DB=fastapi
      volumes:
        - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: